### ISSUE TITLE
dubhFunctions contains two sev functions

### ISSUE THREAD

**Issue by jbostrus** [fireundubh/xedit-scripts#1]
I believe there is a typo in the dubhFunctions file. It contains two functions called sev but i believe one is supposed to be snv in reference to the comment before it for SetNativeValue.

I have created and submitted a pull request.

**Comment by fireundubh** [comment]
Didn't see a pull request, but fixed. Thanks.

**Comment by jbostrus** [comment]
Ya that was my bad. Still don't really understand how to use github that well. I made the change and forgot to hit the merge button to send the pull request. Oh well glad it's fixed.
