### ISSUE TITLE
Undeclared Identifier 'FreeAndNil'

### ISSUE THREAD

**Issue by CyborgArmGon** [fireundubh/xedit-scripts#3]
Full message is:

"Exception in unit  line -1: Error in unit 'dubhFunctions' on line 533 : Undeclared Identifier 'FreeAndNil'"

Happens on pretty much every mod I try to apply the script on :/

**Comment by CyborgArmGon** [comment]
Exception in unit  line -1: Error in unit 'BashTagsDetector' on line 490 : Undeclared Identifier 'FreeAndNil'

Also :/

**Comment by fireundubh** [comment]
You need mteFunctions, too (linked in the description at the top of the script), or xEdit Pro.
